---
hostname: leaf2
os: junos
port: 12223
host: 127.0.0.1
router_id: "10.0.1.2"
asn: 131092

interfaces:
  - name: "lo0"
    ip_address: "10.0.1.2/32"
    description: ""
  - name: "ge-0/0/1"
    ip_address: "10.12.0.2/30"
    description: "to spine1"
  - name: "ge-0/0/2"
    ip_address: "10.22.0.2/30"
    description: "to spine2"
  - name: "ge-0/0/3"
    ip_address: "10.33.0.1/24"
    description: "to base300"

bgp_neighbors:
  - name: "spine1"
    ip: 10.12.0.1
    asn: 65546
  - name: "spine2"
    ip: 10.22.0.1
    asn: 65556
