---
hostname: spine2
os: junos
port: 12222
host: 127.0.0.1
router_id: "10.0.0.2"
asn: 65556

interfaces:
  - name: "lo0"
    ip_address: "10.0.0.2/32"
    description: ""
  - name: "ge-0/0/1"
    ip_address: "10.21.0.1/30"
    description: "to leaf1"
  - name: "ge-0/0/2"
    ip_address: "10.22.0.1/30"
    description: "to leaf2"
  - name: "ge-0/0/3"
    ip_address: "10.23.0.1/30"
    description: "to leaf3"


bgp_neighbors:
  - name: "leaf1"
    ip: 10.21.0.2
    asn: 131082
  - name: "leaf2"
    ip: 10.22.0.2
    asn: 131092
  - name: "leaf3"
    ip: 10.23.0.2
    asn: 131102
